### ISSUE TITLE
Bumping to Node 20.10.0 LTS recommended runtime

### ISSUE THREAD

**Issue by bluefield-creator** [Polytoria/CommunityBot#110]
NodeJS V16 is scheduled to go off the hook real soon
![image](https://github.com/Polytoria/CommunityBot/assets/48862659/6e06a06c-dc6b-45aa-a36e-69d7d4bdb1d4)

The ideal thing would be to bump to Node V20 to keep up with basic security updates & support from the packages we run as well.

**Comment by bluefield-creator** [comment]
Well, in fact, its _off the hook already_, upgrading should be a priority! ASAP!

**Comment by StarManTheGamer** [comment]
Thanks for reporting this issue. I will look into upgrading the current node we're using. This is partly my fault, I didn't realize that v16 was being discontinued so soon.

**Comment by StarManTheGamer** [comment]
I'm completing the node upgrade on both my server and computer, and also updating the README to use Node 20.10.0 LTS. I was currently using v18 for both machines, so I wasn't totally behind on v16.

Thank you for bringing this to my attention.

**Comment by bluefield-creator** [comment]
> I'm completing the node upgrade on both my server and computer, and also updating the README to use Node 20.10.0 LTS. I was currently using v18 for both machines, so I wasn't totally behind on v16.
> 
> Thank you for bringing this to my attention.

Yeah, I called this out in Jan 2023 as well (Ref; #102) to bump to node 18 lol
