### ISSUE TITLE
Rewrite proposal

### ISSUE THREAD

**Issue by bluefield-creator** [Polytoria/CommunityBot#31]
Currently, the detects new commands by loading them manually. 

A more object-oriented approach would be useful to give more data as of what each command does.

Things like `help` commands rely on this data and would be easily automatized as well as a more reliable source to maintain.

Thoughts?

**Comment by SK-Fast** [comment]
> You barely even helped us last time, and I had to sorta take over reviewing devpixels code because whenever I asked you I was getting ignored, is this going to happen again? Why another rewrite if the bot is perfectly fine?

shutup

Do you have examples of object-oriented Discord bot crap? like a repo or example code so I can know more.

**Comment by StarManTheGamer** [comment]
We’ll talk this over

**Comment by SK-Fast** [comment]
Do you have example of object-oriented Discord bots? I want to know how does it look like. You can give me a example code or repo if ya want to.

**Comment by bluefield-creator** [comment]
Too lazy to figure out, i'll send a barebones template someday
